#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sphinxcontrib-httpdomain
Version  : 1.4.0
Release  : 8
URL      : https://pypi.python.org/packages/source/s/sphinxcontrib-httpdomain/sphinxcontrib-httpdomain-1.4.0.tar.gz
Source0  : https://pypi.python.org/packages/source/s/sphinxcontrib-httpdomain/sphinxcontrib-httpdomain-1.4.0.tar.gz
Summary  : Sphinx domain for HTTP APIs
Group    : Development/Tools
License  : BSD-2-Clause
Requires: sphinxcontrib-httpdomain-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
sphinxcontrib.httpdomain --- Documenting RESTful HTTP APIs
==========================================================

%package python
Summary: python components for the sphinxcontrib-httpdomain package.
Group: Default

%description python
python components for the sphinxcontrib-httpdomain package.


%prep
%setup -q -n sphinxcontrib-httpdomain-1.4.0

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
